import type { Metadata } from "next";
// import localFont from "next/font/local";
import "../globals.css";
import { Readex_Pro } from 'next/font/google';
// import Providers from "@/feature/Shared/auth/Providers";
// import { Toaster } from "@/components/ui/sooner";
// import Navbar from "@/feature/Shared/Navbar";
// import AuthButtons from "@/feature/Shared/auth/AuthButtons";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ReadexPro = Readex_Pro({
	subsets: ['latin'],
	weight: ['200', '300', '400', '500', '600', '700']
})

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
            className={`${ReadexPro.className} antialiased !bg-gradient h-screen w-screen flex justify-center items-center`}
    >
      <body> 
          {children}
      </body>
    </html>
  );
}
